# 工作流名称
name: Sync-Images-to-SWR
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images from DockerHub to SWR.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Login to SWR
      uses: docker/login-action@v3
      with:
        registry: swr.cn-north-4.myhuaweicloud.com
        username: ${{ secrets.SWR_USER }}
        password: ${{ secrets.SWR_PASSWORD }}
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to SWR
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://docker.io/idootop/mi-gpt-tts:latest docker://swr.cn-north-4.myhuaweicloud.com/todayhill/mi-gpt-tts:latest
        skopeo copy --all docker://docker.io/idootop/mi-gpt:latest docker://swr.cn-north-4.myhuaweicloud.com/todayhill/mi-gpt:latest
        skopeo copy --all docker://docker.io/consul:1.15.4 docker://swr.cn-north-4.myhuaweicloud.com/todayhill/consul:1.15.4
        skopeo copy --all docker://docker.io/nacos/nacos-server:latest docker://swr.cn-north-4.myhuaweicloud.com/todayhill/nacos-server:latest
